/*
 * This file was automatically generated by EvoSuite
 * Fri Apr 05 01:41:02 GMT 2024
 */

package com.axios.core.tool.text;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.axios.core.tool.text.ArrayIter;
import java.util.NoSuchElementException;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ArrayIter_ESTest extends ArrayIter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Integer[] integerArray0 = new Integer[4];
      Integer integer0 = new Integer(0);
      integerArray0[0] = integer0;
      ArrayIter<Integer> arrayIter0 = new ArrayIter<Integer>(integerArray0);
      Object object0 = arrayIter0.getArray();
      ArrayIter<Object> arrayIter1 = new ArrayIter<Object>(object0, (-1091), (int) integerArray0[0]);
      arrayIter1.next();
      assertTrue(arrayIter0.hasNext());
      assertTrue(arrayIter1.hasNext());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Integer[] integerArray0 = new Integer[4];
      ArrayIter<Integer> arrayIter0 = new ArrayIter<Integer>(integerArray0);
      boolean boolean0 = arrayIter0.hasNext();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Integer[] integerArray0 = new Integer[1];
      ArrayIter<Integer> arrayIter0 = new ArrayIter<Integer>(integerArray0);
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      arrayIter0.forEach(consumer0);
      boolean boolean0 = arrayIter0.hasNext();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArrayIter<String> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<String>((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ArrayIter<Object> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<Object>((Object) null, 1, 1);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Object object0 = new Object();
      ArrayIter<String> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<String>(object0, (-3221), (-3221));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Argument is not an array
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArrayIter<String> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<String>((Object) null, (-178));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArrayIter<Object> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<Object>("", (-769));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Argument is not an array
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ArrayIter<Integer> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<Integer>("^nITs");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Argument is not an array
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[1];
      ArrayIter<String> arrayIter0 = new ArrayIter<String>(stringArray0);
      Object object0 = arrayIter0.getArray();
      ArrayIter<Object> arrayIter1 = new ArrayIter<Object>(object0, 1);
      assertTrue(arrayIter1.hasNext());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[1];
      ArrayIter<String> arrayIter0 = new ArrayIter<String>(stringArray0);
      Object object0 = arrayIter0.getArray();
      ArrayIter<Object> arrayIter1 = new ArrayIter<Object>(object0);
      assertTrue(arrayIter1.hasNext());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Object[] objectArray0 = new Object[1];
      ArrayIter<Object> arrayIter0 = new ArrayIter<Object>(objectArray0);
      arrayIter0.next();
      // Undeclared exception!
      try { 
        arrayIter0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.axios.core.tool.text.ArrayIter", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[8];
      ArrayIter<String> arrayIter0 = new ArrayIter<String>(stringArray0);
      Object object0 = arrayIter0.getArray();
      ArrayIter<Object> arrayIter1 = new ArrayIter<Object>(object0, 0, 0);
      assertTrue(arrayIter1.hasNext());
      
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      arrayIter1.forEachRemaining(consumer0);
      assertTrue(arrayIter0.hasNext());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      ArrayIter<Object> arrayIter0 = new ArrayIter<Object>(objectArray0);
      Object object0 = arrayIter0.getArray();
      ArrayIter<Object> arrayIter1 = new ArrayIter<Object>(object0, 1746, 1746);
      assertFalse(arrayIter1.hasNext());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Integer[] integerArray0 = new Integer[8];
      int int0 = 1;
      ArrayIter<Integer> arrayIter0 = new ArrayIter<Integer>(integerArray0);
      Object object0 = arrayIter0.getArray();
      ArrayIter<Object> arrayIter1 = new ArrayIter<Object>(object0, (-1111), int0);
      assertTrue(arrayIter1.hasNext());
      assertTrue(arrayIter0.hasNext());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      ArrayIter<Object> arrayIter0 = new ArrayIter<Object>(objectArray0);
      arrayIter0.reset();
      assertFalse(arrayIter0.hasNext());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Integer[] integerArray0 = new Integer[6];
      ArrayIter<Integer> arrayIter0 = new ArrayIter<Integer>(integerArray0);
      // Undeclared exception!
      try { 
        arrayIter0.remove();
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // remove() method is not supported
         //
         verifyException("com.axios.core.tool.text.ArrayIter", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ArrayIter<Object> arrayIter0 = null;
      try {
        arrayIter0 = new ArrayIter<Object>((Object) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.lang.reflect.Array", e);
      }
  }
}
